name: build
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: python3 -um build_binary 3.8.13
    - run: python3 -um validate
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}
        path: dist/*

  cirrus:
    strategy:
      matrix:
        job: ['linux arm64', 'macos arm64']
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
    - uses: actions/checkout@v3
    - run: |
        bin/download-cirrus-artifacts \
          --repo "$GITHUB_REPOSITORY" \
          --commit "$GH_COMMIT" \
          --check-name "$CIRRUS_JOB_NAME"
      env:
        CIRRUS_JOB_NAME: ${{ matrix.job }}
        GH_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: 1
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.job }}
        path: dist/*

  collect-and-deploy:
    needs: [build, cirrus]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SENTRY_DEV_INFRA_ASSETS_WRITER }}
    - uses: google-github-actions/setup-gcloud@v0
    - run: bin/upload-artifacts
