name: build
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  build:
    strategy:
      matrix:
        include:
        - {os: macos-latest, py: 3.8.13, build: 1}
        - {os: macos-latest, py: 3.9.13, build: 1}
        - {os: macos-latest, py: 3.10.5, build: 1}
        - {os: ubuntu-latest, py: 3.8.13, build: 1}
        - {os: ubuntu-latest, py: 3.9.13, build: 1}
        - {os: ubuntu-latest, py: 3.10.5, build: 1}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: python3 -um build_binary ${{ matrix.py }} --build ${{ matrix.build }}
    - run: python3 -um validate
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.py }}
        path: dist/*

  cirrus:
    strategy:
      matrix:
        os: [darwin, linux]
        py: [3.8.13, 3.9.13, 3.10.5]
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
    - uses: actions/checkout@v3
    - run: |
        bin/download-cirrus-artifacts \
          --repo "$GITHUB_REPOSITORY" \
          --commit "$GH_COMMIT" \
          --check-name "$CIRRUS_JOB_NAME"
      env:
        CIRRUS_JOB_NAME: ${{ matrix.os }}-${{ matrix.py }}-arm64
        GH_COMMIT: ${{ github.event.pull_request.head.sha || github.sha }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: 1
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}-${{ matrix.py }}-arm64
        path: dist/*

  collect-and-deploy:
    needs: [build, cirrus]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: dist
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SENTRY_DEV_INFRA_ASSETS_WRITER }}
    - uses: google-github-actions/setup-gcloud@v0
    - run: bin/upload-artifacts
