name: build
on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: python3 -m build_binary 3.8.13
    - run: python3 -m validate
    - uses: actions/upload-artifact@v3
      with:
        name: dist-${{ matrix.os }}
        path: dist/*
